import json
import logging
from pathlib import Path

import numpy as np
import tritonclient.grpc as grpcclient

from app.config import settings

logger = logging.getLogger(__name__)

# Path to the label map generated by ml/export_to_onnx.py
_LABELS_PATH = Path(__file__).parent.parent.parent / "ml" / "model_repository" / "plant_disease_model" / "labels.json"

# Fallback label list if labels.json hasn't been generated yet (matches HF model classes)
_FALLBACK_LABELS = {
    "0": "Apple with Apple Scab",
    "1": "Apple with Black Rot",
    "2": "Apple with Cedar Apple Rust",
    "3": "Healthy Apple",
    "4": "Healthy Blueberry Plant",
    "5": "Cherry with Powdery Mildew",
    "6": "Healthy Cherry",
    "7": "Corn with Cercospora Leaf Spot",
    "8": "Corn with Common Rust",
    "9": "Healthy Corn",
    "10": "Corn with Northern Leaf Blight",
    "11": "Grape with Black Rot",
    "12": "Grape with Esca (Black Measles)",
    "13": "Healthy Grape",
    "14": "Grape with Leaf Blight",
    "15": "Orange with Haunglongbing (Citrus Greening)",
    "16": "Peach with Bacterial Spot",
    "17": "Healthy Peach",
    "18": "Bell Pepper with Bacterial Spot",
    "19": "Healthy Bell Pepper",
    "20": "Potato with Early Blight",
    "21": "Healthy Potato",
    "22": "Potato with Late Blight",
    "23": "Healthy Raspberry",
    "24": "Healthy Soybean",
    "25": "Squash with Powdery Mildew",
    "26": "Strawberry with Leaf Scorch",
    "27": "Healthy Strawberry",
    "28": "Tomato with Bacterial Spot",
    "29": "Tomato with Early Blight",
    "30": "Tomato with Late Blight",
    "31": "Tomato with Leaf Mold",
    "32": "Tomato with Septoria Leaf Spot",
    "33": "Tomato with Spider Mites",
    "34": "Tomato with Target Spot",
    "35": "Tomato with Tomato Yellow Leaf Curl Virus",
    "36": "Tomato with Tomato Mosaic Virus",
    "37": "Healthy Tomato",
    "38": "Tomato with Two-spotted Spider Mite",
}


def _load_labels() -> dict:
    """Load label map from generated JSON, fall back to built-in map."""
    if _LABELS_PATH.exists():
        try:
            with open(_LABELS_PATH) as f:
                return json.load(f)
        except Exception as e:
            logger.warning(f"Failed to load labels.json: {e}. Using fallback labels.")
    return _FALLBACK_LABELS


def _parse_label(raw_label: str) -> dict:
    """
    Convert a HuggingFace plant disease label string into structured fields.
    Examples:
        'Healthy Blueberry Plant' -> { plant: 'Blueberry', disease: 'Healthy', is_healthy: True }
        'Tomato with Bacterial Spot' -> { plant: 'Tomato', disease: 'Bacterial Spot', is_healthy: False }
    """
    raw_lower = raw_label.lower()
    is_healthy = "healthy" in raw_lower

    if is_healthy:
        plant = raw_label.replace("Healthy", "").replace("Plant", "").strip().title()
        disease = "Healthy"
    elif " with " in raw_lower:
        parts = raw_label.split(" with ", 1)
        plant = parts[0].strip().title()
        disease = parts[1].strip().title()
    else:
        # Generic fallback
        plant = raw_label
        disease = "Unknown"

    # Map disease name to disease_key format for treatment lookups
    disease_key = f"{plant.lower()}_{disease.lower().replace(' ', '_')}"

    return {
        "plant": plant,
        "disease": disease,
        "disease_key": disease_key,
        "is_healthy": is_healthy,
    }


class TritonInferenceClient:
    def __init__(self):
        self.url = settings.TRITON_SERVER_URL
        self.model_name = settings.MODEL_NAME
        self.model_version = settings.MODEL_VERSION
        self._client = None
        self._labels = _load_labels()
        logger.info(f"TritonInferenceClient initialized. Labels loaded: {len(self._labels)} classes.")

    def _get_client(self):
        if self._client is None:
            try:
                self._client = grpcclient.InferenceServerClient(url=self.url, verbose=False)
                logger.info(f"Connected to Triton server at {self.url}")
            except Exception as e:
                logger.warning(f"Unable to connect to Triton server at {self.url}: {e}")
        return self._client

    def predict(self, tensor: np.ndarray) -> dict:
        """
        Sends a preprocessed image tensor to Triton for inference.
        Falls back to the HuggingFace API mock if Triton is unreachable.
        """
        client = self._get_client()
        if client is None:
            logger.warning("Triton unavailable — using mock prediction.")
            return self._mock_predict()

        try:
            inputs = [grpcclient.InferInput("input_1", tensor.shape, "FP32")]
            inputs[0].set_data_from_numpy(tensor)

            outputs = [grpcclient.InferRequestedOutput("output")]

            response = client.infer(
                model_name=self.model_name,
                model_version=self.model_version,
                inputs=inputs,
                outputs=outputs,
                timeout=5.0,
            )

            logits = response.as_numpy("output")  # shape: (1, num_classes)
            return self._parse_outputs(logits[0])

        except Exception as e:
            logger.error(f"Triton inference failed: {e}. Falling back to mock.")
            return self._mock_predict()

    def _parse_outputs(self, logits: np.ndarray) -> dict:
        """
        Converts raw logit output to structured disease prediction.
        Supports the full 39-class HuggingFace label space.
        """
        # Softmax to convert logits to probabilities
        exp_logits = np.exp(logits - np.max(logits))
        probs = exp_logits / exp_logits.sum()

        top_idx = int(np.argmax(probs))
        top_conf = float(probs[top_idx])
        raw_label = self._labels.get(str(top_idx), f"Unknown Class {top_idx}")
        parsed = _parse_label(raw_label)

        # Top-5 for diagnostics
        top5_idx = np.argsort(probs)[::-1][:5]
        boxes = []  # ONNX classifier doesn't produce bounding boxes; Grad-CAM uses center highlight

        return {
            "species": {
                "name": parsed["plant"],
                "confidence": top_conf,
            },
            "disease": {
                "name": parsed["disease_key"],
                "display_name": parsed["disease"],
                "confidence": top_conf,
                "is_healthy": parsed["is_healthy"],
            },
            "boxes": boxes,
            "top5": [
                {
                    "label": self._labels.get(str(i), f"Class {i}"),
                    "confidence": float(probs[i]),
                }
                for i in top5_idx
            ],
        }

    def _mock_predict(self) -> dict:
        """Fallback mock response — used only when Triton server is unreachable."""
        logger.info("Generating mock diagnostics response (Triton simulation mode).")
        return {
            "species": {"name": "Tomato", "confidence": 0.982},
            "disease": {
                "name": "tomato_early_blight",
                "display_name": "Early Blight",
                "confidence": 0.941,
                "is_healthy": False,
            },
            "boxes": [{"box": [25.0, 40.0, 180.0, 200.0], "confidence": 0.89}],
            "top5": [],
        }
